### ISSUE TITLE
missing else statements

### ISSUE THREAD

**Issue by pydotpy** [dcfitz11/evil-twin#2]
https://github.com/dcfitz11/evil-twin/blob/501303c0e05f2d9c6708b49d1faf694a463efed3/evil-twin.py#L71

input in the install classes is missing an else statement. Input other than  y or n will crash the program

**Comment by dcfitz11** [comment]
Thanks for reviewing! Good find. It's now fixed.

**Comment by pydotpy** [comment]
For sure. This response is mainly for experience using github features hahah
